# .pre-commit-config.yaml
- repo: https://github.com/pre-commit/mirrors-flake8
  rev: v3.9.2
  hooks:
    - id: flake8
      args: ['--max-line-length=88']

- repo: https://github.com/pre-commit/pytest
  rev: v4.6.1
  hooks:
    - id: pytest
      args: ['--maxfail=1', '--disable-warnings', '-q', '--cov=world', '--cov-report=term-missing', '--cov-fail-under=80']

- repo: https://github.com/pre-commit/mirrors-black
  rev: v21.7b0
  hooks:
    - id: black

